name: build

on:
  push:
    branches:
      - "master"
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          6.0.x
          7.0.x
        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
    - name: Pack NuGet artifacts
      if: startsWith(github.ref, 'refs/tags/v')
      run: dotnet pack -c Release --no-build --include-symbols -p:SymbolPackageFormat=snupkg -p:ContinuousIntegrationBuild=true -o packages/
    - name: Publish
      if: startsWith(github.ref, 'refs/tags/v')
      run: dotnet nuget push "packages/*.nupkg" -k ${{ secrets.NUGET_APIKEY }} -s https://api.nuget.org/v3/index.json
